### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by A21z**

### CODE REVIEW

**Comment by A21z** [comment]
Hey @signorekai, thank you for contributing! Do you mind if I merge back your work for a 2.0.0 release?

**Comment by signorekai** [comment]
Hey sure, go ahead. You might want to edit the readme though, I changed the
git clone URL to my repository.

**Comment by signorekai** [comment]
By the way, I disabled the IP checking because I was too busy/lazy to get
it working. Might want to reimplement that too; it's on my roadmap but I
haven't got the time.

**Comment by A21z** [comment]
Great, thanks. 
I've refactored a bit and re-activated IP checking for Bitbucket. I don't know Contentful enough but feel free to add it later.
I'll merge this once I've run some thorough manual testing.

**Comment by A21z** [comment]
I've run some tests, it should be good now.
Also fixed https://github.com/A21z/node-cd/issues/10

**Pull request merged**
